/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/storage/localDB.web`; params?: Router.UnknownInputParams; } | { pathname: `/../src/services/gpsService.web`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/MapScreen.web`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/captain` | `/captain`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mate` | `/mate`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/triplog` | `/triplog`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/storage/localDB.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/services/gpsService.web`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/screens/MapScreen.web`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/captain` | `/captain`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/mate` | `/mate`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/triplog` | `/triplog`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../src/storage/localDB.web${`?${string}` | `#${string}` | ''}` | `/../src/services/gpsService.web${`?${string}` | `#${string}` | ''}` | `/../src/screens/MapScreen.web${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/captain${`?${string}` | `#${string}` | ''}` | `/captain${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/mate${`?${string}` | `#${string}` | ''}` | `/mate${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/triplog${`?${string}` | `#${string}` | ''}` | `/triplog${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../src/storage/localDB.web`; params?: Router.UnknownInputParams; } | { pathname: `/../src/services/gpsService.web`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/MapScreen.web`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/captain` | `/captain`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/mate` | `/mate`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/triplog` | `/triplog`; params?: Router.UnknownInputParams; };
    }
  }
}
